[GLOBAL]
pants_version = "2.13.0.dev3"
use_deprecated_directory_cli_args_semantics = false
backend_packages.add = [
  "pants.backend.experimental.go",
]
plugins = [
  "toolchain.pants.plugin==0.19.0",
]
# Caching is disabled by default so that desktop builds are not cached. CI caching is enabled in pants.ci.toml.
remote_cache_read = false
remote_cache_write = false
# We want to continue to get logs when remote caching errors.
remote_cache_warnings = "backoff"
remote_store_address = "grpcs://cache.toolchain.com:443"
remote_instance_name = "main"
remote_auth_plugin = "toolchain.pants.auth.plugin:toolchain_auth_plugin"

[source]
root_patterns = ["/"]

[anonymous-telemetry]
enabled = true
repo_id = "E6C010FF-E41B-4AFE-9B6C-05F85B219046"

[toolchain-setup]
org = "toolchainlabs"
repo = "remote-api-tools"

[golang]
minimum_expected_version = "1.17"

[buildsense]
collect_platform_data = true
